# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker


trigger: none

variables:
  # Container registry service connection established during pipeline creation
  projectName: 'Mwp.HttpApi.Host'
  disable.coverage.autogenerate: 'true'

jobs:
  - job: RunTests
    displayName: Run Tests
    continueOnError: false
    pool:
      vmImage: 'windows-latest'
      
    steps:
    - task: DotNetCoreCLI@2      
      displayName: Restore Nuget Package
      inputs:
        command: 'restore'
        projects: '**/$(projectName).csproj'
        feedsToUse: 'config'
        nugetConfigPath: 'NuGet.Config'
        externalFeedCredentials: 'AbpCommercial'

    - task: CmdLine@2
      displayName: Start storage emulator
      inputs:
        script: |
            echo Starting MsSql localdb...  
            
            sqllocaldb create MSSQLLocalDB
            sqllocaldb start MSSQLLocalDB
            sqllocaldb info MSSQLLocalDB
            
            echo Starting Storage Emulator...
            "C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" start
            
            echo Storage Emulator started...
            
    - task: DotNetCoreCLI@2
      displayName: Run tests
      inputs:
        command: 'test'
        projects: '**/*.Tests.csproj'
        arguments: '--collect:"XPlat Code Coverage" --settings coverlet.runsettings'

    - task: reportgenerator@4
      displayName: Generate coverage report
      inputs:
        reports: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
        targetdir: 'coveragereport'

    - task: PublishCodeCoverageResults@1
      displayName: Publish coverage report
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '**/Cobertura.xml'
        reportDirectory: 'coveragereport'
